name: mel
description: A new Flutter project.
version: 1.0.0+1

environment:
  sdk: ">=2.1.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  json_serializable: ^3.2.3
  build_runner: ^1.7.2
  firebase_auth: ^0.14.0+5
  data_connection_checker: ^0.3.4
  firebase_core: ^0.4.0+9
  provider: ^3.2.0
  shared_preferences: ^0.5.4+9
  cloud_firestore: ^0.13.0+1

  # The following adds the Cupertino Icons font to your application.
  # Use with the CupertinoIcons class for iOS style icons.
  cupertino_icons: ^0.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter
  equatable: ^0.6.1
  dartz: ^0.8.7
  meta: ^1.1.7
  mockito: ^4.1.1
  get_it: ^3.0.3

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:
  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true
